### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ikaevalko** [Jonkke/tsoha-noteapp#1]
Projekti ladattu 30.9.2019 klo 18:05

### Kirjautuminen ja rekisteröityminen:

- Linkit on aseteltu järkevästi ja ne on helppo löytää
- Uuden käyttäjän luominen onnistuu
- Rekisteröinnissä on hyvät validoinnit syötteille
- Kirjautuminen toimii tarkoituksenmukaisesti sekä testitunnuksilla että uudella käyttäjällä
- Salasanojen käsittely tehdään turvallisesti Bcryptillä
- Pienenä parannuksena voisi olla käyttäjänimen näyttäminen navigaatiopalkissa

### Muistiinpanot:

- Linkkien asettelu on järkevää
- Note-taululla on toimivat CRUD-ominaisuudet
- Lomakkeilla on yksinkertainen, mutta aiheeseen sopiva validointi
- Linkit muistiinpanojen lisäämiseen, muokkaamiseen ja poistamiseen on suojattu

Ohjelmakoodi on helppolukuista - funktioiden ja luokkien nimet ovat kuvaavia ja nimeämiskäytänteet vaikuttavat johdonmukaisilta. Sivujen HTML-elementtejä käytetään oikeisiin tarkoituksiin.

Kaikki käyttötapaukset (pl. WIP) on mahdollista tehdä sovelluksen nykyisessä versiossa. Sovelluksesta löytyi kuitenkin yksi bugi. Kun muistiinpano on päivitetty, listaussivulle palatessa tietokannasta haetaan _kaikkien_ käyttäjien olemassa olevat muistiinpanot listattavaksi. Ongelma liittyy notes_update -funktion paluuarvoon.

**Comment by ghost** [comment]
Kiitos palautteesta! Itseltä olikin mennyt tuo päivityksen jälkeen tapahtuva kaikkien muistiinpanojen hakeminen kokonaan ohi silmien.
