### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by EssKayz** [Jonkke/tsoha-noteapp#2]
### Koodi ladattu : 10/11/2019 13:53

# Herokussa testailu
### User storyt
- [x] Käyttäjä voi luoda itselleen käyttäjätunnuksen ja salasanan
- [x] Käyttäjä voi kirjautua sisään tai ulos luodulla tunnuksella ja salasanalla
- [x] Käyttäjä voi luoda uusia muistiinpanoja, jotka ovat oletuksena vain ne luoneen käyttäjän muokattavissa ja luettavissa
- [ ] Kirjoitusoikeudet olemassa olevaan muistiinpanoon omaava käyttäjä voi muokata muistiinpanon sisältöä
- Tässä tuli Internal Server Error
- [x] Muistiinpanoihin voi liittää tageja
- [x] Käyttäjä voi etsiä tagien avulla muistiinpanoja, joihin hänellä on lukuoikeus
- Tämä toimi alkuun epäintuitiivisesti, haku ei salli osittaisia osumia, esim "tagi" sana ei palauta "tagi1" ja "tagi2", ja ilman herokussa löytyvää muistiinpanoa joka selittää miten haku toimii, en tiedä olisinko keksinyt tätä
- [ ] Käyttäjä voi suodattaa muistiinpanoja vain tietyllä aikavälillä luotuihin tai päivitettyihin muistiinpanoihin (WIP)
- [ ] Käyttäjä voi lisätä muita käyttäjiä kontaktilistalleen, mikäli hänellä on hallussaan toisen käyttäjän viisikirjaiminen tunnistusmerkkijono (WIP)
- [ ] Käyttäjä voi halutessaan jakaa muistiinpanon muiden käyttäjien kanssa, joko pelkällä lukuoikeudella tai myös kirjoitusoikeudella (WIP)

### User storyjen ulkopuolelta löytyvät ominaisuudet 
- [ ] Muistiinpanon voi poistaa
- Tässä tuli taas internal server erroria, vaikkakin taisi poistua sitten oikeasti, mutta piti käsin navigoida virhesivulta pois

# Koodin tarkastelu
Repositoriossa löytyvillä ohjeilla ei saanut ohjelmaa toimimaan windowssilla, joutui erikseen etsimään ohjeet.
- Samat bugit myös omalla koneella, eli editointi ja delete aiheuttavat jinja exceptionieita.
  - "return render_template("notes/notelist.html", notes=notes)" sisältää syyn siihen, miksei edit toimi notes_update metodissa
  - tasan sama koodinpätkä löytyy myös notes_delete kentästä.
  - Syy siihen mikseivät nämä toimi, löytyy taas itse notelist.html tiedostosta.
  
- NoteForm formissa ei validointia "content" kentälle?
- Ohjelmakoodi oli helppolukuista, metodien nimeämispolitiikka oli yhdenmukainen. 
- Sivu on yksinkertainen navigoida, kaikkeen on helppo päästä käsiksi
- Toisaalta, sivu tuntuu kovin yksinkertaiselta myös toiminnallisuuden osalta toistaiseksi, sillä sivulla on ainoastaan mahdollista lisätä muistiinpanoja, editoida ja poistaa muistiinpanoja.

# Yleistä
- Readme.md voisi ehkä lisätä ohjeet Windowssille
- Kuvauksessa puhutaan ajanseuraamisesta, mutta en löydä ohjelmasta viitteitä mihinkään ajanseurantaan, enkä myöskään keksi miten tuohon tietokantatauluun tämä toimisi yhteen?

**Comment by ghost** [comment]
Kiitos kattavasta palautteesta ja bugi-ilmosta! Proju on tosiaan jäänyt vähän raakileeksi aiotusta, katsotaan mitä kaikkea tässä muutaman päivän aikana vielä ehtii saamaan sisään :)
